// packages/doggy-nav-main/pages/recommend.vue
<template>
  <div class="container">
    <el-card>
        <el-form ref="ruleForm" label-width="100px" :model="form" :rules="rules"  v-loading="formLoading">

          <el-form-item label="网站链接" prop="href">
            <el-input placeholder="http://www.baidu.com/" v-model="form.href" @blur="getNavInfo" />
            <span style="color: red">输入链接自动爬取信息</span>
          </el-form-item>

          <el-form-item label="网站标签" prop="tags">
            <el-select
              v-model="form.tags"
              multiple
              :multiple-limit="5"
              filterable
              allow-create
              default-first-option
              placeholder="输入网站标签，最多5个">
              <el-option
                v-for="item in tags"
                :key="item.value"
                :label="item.label"
                :value="item.value">
              </el-option>
            </el-select>
          </el-form-item>
          <el-form-item label="网站名称" prop="name">
            <el-input placeholder="输入网站名称" v-model="form.name" />
          </el-form-item>

          <el-form-item label="网站logo" prop="logo">
            <el-input placeholder="输入网站logo" v-model="form.logo" />
            <img style="max-width: 30px;" :src="form.logo" />
          </el-form-item>
          <el-form-item label="网站描述" prop="desc">
            <el-input placeholder="一句话网站描述，15个字以内" v-model="form.desc" />
          </el-form-item>
          <el-form-item label="网站分类" prop="categoryId">
            <el-select v-model="form.categoryId" placeholder="请选择" filterable>
              <el-option-group
                v-for="group in categorys"
                :key="group._id"
                :label="group.name"
              >
                <el-option
                  v-for="item in group.children"
                  :key="item._id"
                  :label="item.name"
                  :value="item._id"
                ></el-option>
              </el-option-group>
            </el-select>
          </el-form-item>
          <el-form-item label="推荐人名称" prop="authorName">
            <el-input placeholder="填写你推广的名称" v-model="form.authorName" />
          </el-form-item>
          <el-form-item label="推荐人网站" prop="authorUrl">
            <el-input placeholder="填写你要推广的链接" v-model="form.authorUrl" />
          </el-form-item>
          <el-form-item label="网站详情" prop="detail">
            <el-input type="textarea" placeholder="输入网站详情" v-model="form.detail" />
          </el-form-item>
          <el-form-item>
            <el-button type="primary" :loading="loading" @click="addNav('ruleForm')">
              提交
            </el-button>
          </el-form-item>
        </el-form>
      </el-card>
  </div>
</template>

<script>
import axios from "../plugins/axios";
import {API_NAV, API_NAV_REPTILE, API_TAG_LIST} from "../api";

export default {
  name: "recommend",
  data() {
    return {
      loading: false,
      formLoading: false,
      categorys: [],
      tags: [],
      form: {
        href: '',
        categoryId: '',
        name: '',
        tags: [],
        logo: '',
        desc: '',
        authorName: '',
        authorUrl: ''
      },
      rules: {
        href: [
          { required: true, message: '请输入url', trigger: 'blur' },
          {
            pattern: /(http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?/,
            message: '请输入正确的url',
          },
        ],
        tags: [
          { required: true, message: '请输入标签', trigger: 'blur' },
        ],
        name: [{ required: true, message: '请输入名称', trigger: 'blur' },],
        desc: [{ required: true, message: '请输入描述', trigger: 'blur' },],
        logo: [{ required: true, message: '请输入logo', trigger: 'blur' },],
        authorUrl: [
          {
            pattern: /(http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?/,
            message: '请输入正确的url',
            trigger: 'change'
          },
        ],
        authorName: [
          {
            pattern: /^[\u4e00-\u9fa5]{2,6}$/,
            message: '作者名称在2个字到6个字以内',
            trigger: 'change'
          },
        ],
      },
      isMoreForm: false,
    }
  },
  methods: {
    async getTags() {
      const res = await axios.get(API_TAG_LIST)
      if (res.code === 1) {
        let data = res.data?.data
        data = data.map(item=> {
          item.value = item.name
          item.label = item.name
          return item
        })
        this.tags = res.data?.data
      }
    },
    async getCategorys() {
      const { data } = await this.$api.getCategoryList()
      this.categorys = data
    },
    async addNav(formName) {
      this.$refs[formName].validate(async (valid) => {
        if (valid) {
          this.loading = true
          // 判断编辑还是更新

          const res = await axios.post(API_NAV, this.form)
          if (res.code === 0) {
            this.$message.error(`${res.msg}`)
          } else {
            this.$message(`感谢您的支持，请等待后台审核通过！`)
            this.$refs.ruleForm.resetFields()
          }
          this.loading = false
          this.$emit('update:show', false)
          this.$emit('submit')
        } else {
          return false
        }
      })
    },
    async getNavInfo() {
      const { href: url } = this.form
      if (!url) return
      this.formLoading = true
      try {
        const { data } = await axios.get(API_NAV_REPTILE + `?url=${url}`)
        this.form.logo = `https://www.google.com/s2/favicons?domain=${url}`
        this.form.name = data?.name
        this.form.desc = data?.desc
      } catch (e) {
        this.$message.error('请求超时')
        this.$emit('update:show', false)
      }
      this.formLoading = false
    }
  },
  created() {
    this.getTags()
    this.getCategorys()
  },
}
</script>

<style scoped>
.container {
  margin: 30px;
}
</style>

// packages/doggy-nav-main/pages/recommend/index.tsx
'use client'
import { useState } from 'react'
import {
  Card,
  Form,
  Input,
  Select,
  Button,
  Message,
  Spin,
} from '@arco-design/web-react'
import axios from '@/utils/axios'
import { API_NAV, API_NAV_REPTILE } from '@/utils/api'
import { useAtom } from 'jotai'
import { RecommendFormValues } from '@/types'
import { categoriesAtom, tagsAtom } from '@/store/store'

const FormItem = Form.Item

export default function Recommend() {
  const [loading, setLoading] = useState(false)
  const [formLoading, setFormLoading] = useState(false)
  const [categories] = useAtom(categoriesAtom)
  const [tags] = useAtom(tagsAtom)
  const [form] = Form.useForm()

  const addNav = async (values: RecommendFormValues) => {
    setLoading(true)
    const res = await axios.post(API_NAV, values)
    if (res.data.code === 0) {
      Message.error(`${res.data.msg}`)
    } else {
      Message.success('感谢您的支持，请等待后台审核通过！')
      form.resetFields()
    }
    setLoading(false)
  }

  const getNavInfo = async () => {
    const url = form.getFieldValue('href')
    if (!url) return
    setFormLoading(true)
    try {
      const { data } = await axios.get(`${API_NAV_REPTILE}?url=${url}`)
      form.setFieldsValue({
        logo: `https://www.google.com/s2/favicons?domain=${url}`,
        name: data?.name,
        desc: data?.desc,
      })
    } catch (e) {
      Message.error('请求超时')
    }
    setFormLoading(false)
  }

  const rules = {
    href: [
      { required: true, message: '请输入url' },
      {
        pattern:
          /(http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-.,@?^=%&:/~\+#]*[\w\-@?^=%&/~\+#])?/,
        message: '请输入正确的url',
      },
    ],
    tags: [{ required: true, message: '请输入标签' }],
    name: [{ required: true, message: '请输入名称' }],
    desc: [{ required: true, message: '请输入描述' }],
    logo: [{ required: true, message: '请输入logo' }],
    authorUrl: [
      {
        pattern:
          /(http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-.,@?^=%&:/~\+#]*[\w\-@?^=%&/~\+#])?/,
        message: '请输入正确的url',
      },
    ],
    authorName: [
      {
        pattern: /^[\u4e00-\u9fa5]{2,6}$/,
        message: '作者名称在2个字到6个字以内',
      },
    ],
  }

  return (
    <div className="container p-4">
      <Card>
        <Form form={form} layout="vertical" onSubmit={addNav}>
          {formLoading && <Spin />}
          <FormItem label="网站链接" field="href" rules={rules.href}>
            <Input placeholder="http://www.baidu.com/" onBlur={getNavInfo} />
          </FormItem>
          <FormItem label="网站标签" field="tags" rules={rules.tags}>
            <Select mode="multiple" showSearch allowCreate placeholder="输入网站标签，最多5个">
              {tags.map((item) => (
                <Select.Option key={item.name} value={item.name}>
                  {item.label}
                </Select.Option>
              ))}
            </Select>
          </FormItem>
          <FormItem label="网站名称" field="name" rules={rules.name}>
            <Input placeholder="输入网站名称" />
          </FormItem>
          <FormItem label="网站logo" field="logo" rules={rules.logo}>
            <Input placeholder="输入网站logo" />
          </FormItem>
          <FormItem label="网站描述" field="desc" rules={rules.desc}>
            <Input placeholder="一句话网站描述，15个字以内" />
          </FormItem>
          <FormItem label="网站分类" field="categoryId">
            <Select placeholder="请选择" showSearch>
              {categories.map((group) => (
                <Select.OptGroup key={group._id} label={group.name}>
                  {group.children?.map((item) => (
                    <Select.Option key={item._id} value={item._id}>
                      {item.name}
                    </Select.Option>
                  ))}
                </Select.OptGroup>
              ))}
            </Select>
          </FormItem>
          <FormItem label="推荐人名称" field="authorName" rules={rules.authorName}>
            <Input placeholder="填写你推广的名称" />
          </FormItem>
          <FormItem label="推荐人网站" field="authorUrl" rules={rules.authorUrl}>
            <Input placeholder="填写你要推广的链接" />
          </FormItem>
          <FormItem label="网站详情" field="detail">
            <Input.TextArea placeholder="输入网站详情" />
          </FormItem>
          <FormItem>
            <Button type="primary" htmlType="submit" loading={loading}>
              提交
            </Button>
          </FormItem>
        </Form>
      </Card>
    </div>
  )
}
