// packages/doggy-nav-main/components/Affiche.vue
<template>
  <div class="affiche" v-if="show">
    <el-carousel
    height="30px"
    direction="vertical"
    indicator-position="none"
  >
    <el-carousel-item>
      <p class="medium">
        一个好的产品要经历千锤百炼，我们需要你的建议。<a
          class="link"
          href="https://github.com/MARVElOUS-DEV/doggy-nav"
          target="_blank"
          >去围观</a
        >
      </p>
    </el-carousel-item>
    <el-carousel-item>
      <p class="medium">
        支持提交网站带个人信息了，欢迎大家提交网站
        <a
          class="link"
          href="/recommend"
          >去提交</a>
      </p>
    </el-carousel-item>
  </el-carousel>
  <i class="el-icon-close" @click="show=false"></i>
  </div>
</template>

<script>
export default {
  data() {
    return {
      show: true
    }
  }
};
</script>

<style lang="scss" scoped>
.affiche {
  width: auto;
  font-size: 14px;
  background: #fff;
  border-radius: 5px;
  padding: 5px 15px;
  display: flex;
  align-items: center;
  p.medium {
    margin: 0;
  }
  i {
    font-size: 18px;
    font-weight: bold;
    cursor: pointer;
  }
  .el-carousel {
    flex: 1;
  }
  .el-carousel__item {
    line-height: 30px;
  }

  .el-carousel__button {
    width: 20px;
    height: 20px;
  }
  .icon-group {
    display: flex;
    float: right;
    color: #999;
    span {
      border: 1px solid #999;
      margin-left: 10px;
      cursor: pointer;
    }
    .icon {
      color: #333;
      margin-left: 20px;
    }
  }
  .link {
    color: #2a97ff;
    text-decoration: underline;
  }
}
</style>

// packages/doggy-nav-main/src/components/Affiche.tsx
import { useState } from 'react';
import { Carousel } from '@arco-design/web-react';
import Link from 'next/link';

export default function Affiche() {
  const [show, setShow] = useState(true);

  if (!show) {
    return null;
  }

  return (
    <div className="affiche flex items-center bg-white rounded-md p-2 text-sm">
      <Carousel direction="vertical" style={{ height: 30, flex: 1 }}>
        <div>
          <p className="m-0">
            一个好的产品要经历千锤百炼，我们需要你的建议。
            <Link
              className="text-blue-500 underline"
              href="https://github.com/MARVElOUS-DEV/doggy-nav"
              target="_blank"
              rel="noopener noreferrer"
            >
              去围观
            </Link>
          </p>
        </div>
        <div>
          <p className="m-0">
            支持提交网站带个人信息了，欢迎大家提交网站
            <Link className="text-blue-500 underline" href="/recommend">
              去提交
            </Link>
          </p>
        </div>
      </Carousel>
      <i className="el-icon-close text-lg font-bold cursor-pointer" onClick={() => setShow(false)}></i>
    </div>
  );
}
