// packages/doggy-nav-main/components/AppNavList.vue
<template>
  <div>
    <el-row type="flex" class="website" :gutter="20">
      <AppNavItem
        v-for="item in list"
        :data="item"
        :key="item._id"
        @handleNavClick="handleNavClick"
        @handleNavStar="handleNavStar"
      />
    </el-row>
  </div>
</template>

<script>
import AppNavItem from "./AppNavItem";
import navActionMixin from "../mixins/navActionMixin";

export default {
  name: 'AppNavList',
  mixins: [navActionMixin],
  components: {
    AppNavItem
  },
  props: {
    list: {
      type: Array,
      default: () => []
    }
  }
};
</script>

<style lang="scss" scoped>
.website {
  flex-wrap: wrap;
}
</style>

// packages/doggy-nav-main/src/components/AppNavList.tsx
import { Grid } from '@arco-design/web-react';
import AppNavItem from './AppNavItem';
import { NavItem } from '@/types';

const { Row } = Grid;

interface AppNavListProps {
  list: NavItem[];
}

export default function AppNavList({ list }: AppNavListProps) {
  const handleNavClick = (item: NavItem) => {
    window.open(item.href, '_blank');
  };

  const handleNavStar = (item: NavItem) => {
    console.log('star', item);
  };

  return (
    <div className="nav-list-container">
      <Row gutter={[24, 24]}>
        {list.map((item) => (
          <AppNavItem
            key={item._id}
            data={item}
            onHandleNavClick={handleNavClick}
            onHandleNavStar={handleNavStar}
          />
        ))}
      </Row>
    </div>
  );
}
