// packages/doggy-nav-main/components/NavRankingList.vue
<template>
  <div class="nav-ranking-list">
    <el-row :gutter="20">
      <el-col :md="8" :sm="12">
        <el-card class="box-card" shadow="never">
          <div slot="header" class="clearfix">
            <span>最新导航</span>
          </div>
          <div v-for="item in data.news" class="text item" :key="item.name">
           <nav-ranking :data="item" />
          </div>
        </el-card>
      </el-col>
      <el-col :md="8" :sm="12">
        <el-card class="box-card" shadow="never">
          <div slot="header" class="clearfix">
            <span>点击最多导航</span>
          </div>
          <div v-for="item in data.view" class="text item" :key="item.name">
            <nav-ranking :data="item" count-type="view" />
          </div>
        </el-card>
      </el-col>
      <el-col :md="8" :sm="12">
        <el-card class="box-card" shadow="never">
          <div slot="header" class="clearfix">
            <span>点赞最多导航</span>
          </div>
          <div v-for="item in data.star" class="text item" :key="item.name">
            <nav-ranking :data="item" count-type="star" />
          </div>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script>
import NavRanking from "./NavRanking";
export default {
  name: "NavRankingList",
  components: {NavRanking},
  props: {
    data: {
      type: Object,
      default: {
        view: [],
        star: [],
        news: []
      }
    }
  },
}
</script>

<style lang="scss" scoped>
.nav-ranking-list {
  .el-card {
    margin-top: 30px;
  }
  .el-card__header {
    span {
      font-size: 18px;
      font-weight: 500;
    }
  }
}
</style>

// packages/doggy-nav-main/src/components/NavRankingList.tsx
import { Card, Grid } from '@arco-design/web-react';
import NavRanking from './NavRanking';
import { NavItem } from '@/types';
import { useTranslation } from 'react-i18next';

const { Row, Col } = Grid;

interface NavRankingListProps {
  data: {
    news: NavItem[];
    view: NavItem[];
    star: NavItem[];
  };
}

export default function NavRankingList({ data }: NavRankingListProps) {
  const { t } = useTranslation();

  return (
    <div className="nav-ranking-list">
      <Row gutter={20}>
        <Col md={8} sm={12}>
          <Card title={t('latest')} bordered={false} className="mt-8">
            {data.news.map((item) => (
              <NavRanking key={item.name} data={item} />
            ))}
          </Card>
        </Col>
        <Col md={8} sm={12}>
          <Card title={t('most_clicks')} bordered={false} className="mt-8">
            {data.view.map((item) => (
              <NavRanking key={item.name} data={item} countType="view" />
            ))}
          </Card>
        </Col>
        <Col md={8} sm={12}>
          <Card title={t('most_likes')} bordered={false} className="mt-8">
            {data.star.map((item) => (
              <NavRanking key={item.name} data={item} countType="star" />
            ))}
          </Card>
        </Col>
      </Row>
    </div>
  );
}
